{
 "title": "My Electrical Data",
 "time": { "from": "2020-12-07T23:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   { "name": "pdl", "label": "Point de livraison", "query": "25256439806760" },
   { "name": "price_STD", "label": "€ / kWh Base", "query": "0.145907" },
   { "name": "price_HC", "label": "€ / kWh (HC)", "query": "0.124364" },
   { "name": "price_HP", "label": "€ / kWh (HP)", "query": "0.164915" },
   { "name": "surface_maison", "label": "Surface de la maison", "query": "75" }
  ]
 },
 "panels": [
  {
   "title": "Consommation Heures Pleines",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumption_detail",
     "query": "SELECT sum(\"Wh\") FROM \"consumption_detail\" WHERE (\"measure_type\" = 'HP' AND \"usage_point_id\" =~ /^$pdl$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "measure_type", "operator": "=", "value": "HP" },
      { "condition": "AND", "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" }
     ]
    }
   ]
  },
  {
   "title": "Heures Pleines ($price_HP€/kWh)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumption_detail",
     "query": "SELECT sum(\"Wh\") *$price_HP FROM \"consumption_detail\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"measure_type\" = 'HP') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HP" }
     ]
    }
   ]
  },
  {
   "title": "Tarif HC/HP",
   "type": "farski-blendstat-panel",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "HC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumption_detail",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HC" }
     ]
    },
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumption_detail",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HP" }
     ]
    }
   ]
  },
  {
   "title": "Classe Energetique",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "consumption",
     "query": "SELECT sum(\"Wh\")  / $surface_maison /1000 FROM \"RETENTION\".\"consumption\" WHERE (\"usage_point_id\" =~ /^$pdl$/) AND time <=now() and time >=now() -365d GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "kWh" ], "type": "field" },
       { "params": [ " / $surface_maison" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" }
     ]
    }
   ]
  },
  {
   "title": "Répartition HC/HP",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "HP",
     "measurement": "consumption_detail",
     "query": "SELECT sum(\"Wh\") FROM \"consumption_detail\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"measure_type\" = 'HP') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HP" }
     ]
    },
    {
     "alias": "HC",
     "measurement": "consumption_detail",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HC" }
     ]
    }
   ]
  },
  {
   "title": "Consommation Heures Creuses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumption_detail",
     "query": "SELECT sum(\"Wh\") FROM \"RETENTION\".\"consumption_detail\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"measure_type\" = 'HC') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HC" }
     ]
    }
   ]
  },
  {
   "title": "Heures Creuses ($price_HC€/kWh)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumption_detail",
     "query": "SELECT sum(\"kW\") *$price_HC FROM \"consumption_detail\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"measure_type\" = 'HC') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HC" }
     ]
    }
   ]
  },
  {
   "title": "Période Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumption",
     "query": "SELECT sum(\"W\") FROM \"consumption_detail\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" }
     ]
    }
   ]
  },
  {
   "title": "Tarif Base ($price_STD€/kWh)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumption",
     "query": "SELECT sum(\"Wh\") /1000*$price_STD FROM \"RETENTION\".\"consumption\" WHERE (\"usage_point_id\" =~ /^$pdl$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" }
     ]
    }
   ]
  },
  {
   "title": "Base vs HC/HP",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 6 },
   "format": "percent",
   "valueName": "total",
   "targets": [
    {
     "alias": "HC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumption_detail",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HC" }
     ]
    },
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumption_detail",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HP" }
     ]
    },
    {
     "alias": "STD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consumption",
     "query": "SELECT sum(\"Wh\") /1000*$price_STD FROM \"RETENTION\".\"consumption\" WHERE (\"usage_point_id\" =~ /^$pdl$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" }
     ]
    }
   ]
  },
  {
   "title": "Electricity Consumption - in (k)Wh",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "HC",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "consumption_detail",
     "select": [
      [
       { "params": [ "W" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HC" }
     ],
     "tz": "Europe/Paris"
    },
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "consumption_detail",
     "query": "SELECT sum(\"W\") FROM \"consumption_detail\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"measure_type\" = 'HP') AND $timeFilter GROUP BY time(30m) fill(none) tz('America/New York')",
     "select": [
      [
       { "params": [ "W" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HP" }
     ],
     "tz": "Europe/Paris"
    }
   ]
  },
  {
   "title": "Electricity Consumption - per Day (k)Wh",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "Watt/Day",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "consumption",
     "query": "SELECT value FROM \"consumption\" WHERE (\"usage_point_id\" =~ /^$pdl$/) AND $timeFilter GROUP BY time(1d) fill(null) ",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" }
     ]
    }
   ]
  },
  {
   "title": "2023",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "2022",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 9, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "2021",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Consommation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "consumption",
     "query": "SELECT sum(\"kWh\") FROM \"RETENTION\".\"consumption\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"year\" = '2023') ",
     "select": [
      [
       { "params": [ "kW" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Coût (Hors forfait)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "consumption",
     "query": "SELECT sum(\"price\") FROM \"RETENTION\".\"consumption\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"year\" = '2023') ",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Ratio",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "current_year",
     "measurement": "consumption",
     "query": "SELECT sum(\"price\") FROM \"RETENTION\".\"consumption\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"year\" = '2023') ",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2020" }
     ]
    },
    {
     "alias": "last_year",
     "query": "SELECT sum(\"price\") FROM \"RETENTION\".\"consumption\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"year\" = '2022') "
    }
   ]
  },
  {
   "title": "Consommation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "consumption",
     "query": "SELECT sum(\"kWh\") FROM \"RETENTION\".\"consumption\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"year\" = '2022') ",
     "select": [
      [
       { "params": [ "kW" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2020" }
     ]
    }
   ]
  },
  {
   "title": "Coût (Hors forfait)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "consumption",
     "query": "SELECT sum(\"price\") FROM \"RETENTION\".\"consumption\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"year\" = '2022') ",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2020" }
     ]
    }
   ]
  },
  {
   "title": "Ratio",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "current_year",
     "measurement": "consumption",
     "query": "SELECT sum(\"price\") FROM \"RETENTION\".\"consumption\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"year\" = '2022') ",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2020" }
     ]
    },
    {
     "alias": "last_year",
     "query": "SELECT sum(\"price\") FROM \"RETENTION\".\"consumption\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"year\" = '2021') "
    }
   ]
  },
  {
   "title": "Consommation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "consumption",
     "query": "SELECT sum(\"kWh\") FROM \"RETENTION\".\"consumption\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"year\" = '2021')",
     "select": [
      [
       { "params": [ "kW" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2019" }
     ]
    }
   ]
  },
  {
   "title": "Coût (Hors forfait)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "€" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "consumption",
     "query": "SELECT sum(\"price\") FROM \"RETENTION\".\"consumption\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"year\" = '2021')",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2019" }
     ]
    }
   ]
  },
  {
   "title": "Consommation mensuelle 2023",
   "type": "table",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "$tag_year",
     "groupBy": [
      { "params": [ "year" ], "type": "tag" },
      { "params": [ "month" ], "type": "tag" }
     ],
     "measurement": "consumption_detail",
     "query": "SELECT sum(\"Wh\") FROM \"RETENTION\".\"consumption_detail\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"year\" = '2023') GROUP BY \"year\", \"month\"",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2021" }
     ]
    }
   ]
  },
  {
   "title": "Consommation mensuelle 2022",
   "type": "table",
   "gridPos": { "h": 14, "w": 9, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "$tag_year",
     "groupBy": [
      { "params": [ "year" ], "type": "tag" },
      { "params": [ "month" ], "type": "tag" }
     ],
     "measurement": "consumption_detail",
     "query": "SELECT sum(\"Wh\") FROM \"RETENTION\".\"consumption_detail\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"year\" = '2022') GROUP BY \"year\", \"month\"",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2020" }
     ]
    }
   ]
  },
  {
   "title": "Consommation mensuelle 2021",
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "$tag_year",
     "groupBy": [
      { "params": [ "year" ], "type": "tag" },
      { "params": [ "month" ], "type": "tag" }
     ],
     "measurement": "consumption_detail",
     "query": "SELECT sum(\"Wh\") FROM \"RETENTION\".\"consumption_detail\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"year\" = '2021') GROUP BY \"year\", \"month\"",
     "select": [
      [
       { "params": [ "Wh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "year", "operator": "=", "value": "2019" }
     ]
    }
   ]
  },
  {
   "title": "Electricity HC Consumption - in (k)Wh",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "HC",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "consumption_detail",
     "select": [
      [
       { "params": [ "W" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HC" }
     ],
     "tz": "Europe/Paris"
    }
   ]
  },
  {
   "title": "Electricity HP Consumption - in (k)Wh",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "HP",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "consumption_detail",
     "query": "SELECT sum(\"W\") FROM \"consumption_detail\" WHERE (\"usage_point_id\" =~ /^$pdl$/ AND \"measure_type\" = 'HP') AND $timeFilter GROUP BY time(30m) fill(none) tz('Europe/Paris')",
     "select": [
      [
       { "params": [ "W" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" },
      { "condition": "AND", "key": "measure_type", "operator": "=", "value": "HP" }
     ],
     "tz": "Europe/Paris"
    }
   ]
  },
  {
   "title": "Electricity Consumption - per Day (k)Wh",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Watt/Day",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "consumption",
     "query": "SELECT value FROM \"consumption_detail\" WHERE (\"usage_point_id\" =~ /^$pdl$/) AND $timeFilter GROUP BY time(1d) fill(null) ",
     "select": [
      [
       { "params": [ "kWh" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "usage_point_id", "operator": "=~", "value": "/^$pdl$/" }
     ]
    }
   ]
  }
 ]
}